In [1]:
import pandas as pd
import numpy as np

In [2]:
#As heterogeneous in terms of (genre, length,...etc) as possible to create better groups of songs.
#Not too big and not too small (typically around 2-3K) songs

In [3]:
df= pd.read_csv('tcc_ceds_music.csv')

In [4]:
df

,Unnamed: 0,artist_name,track_name,release_date,genre,lyrics,len,dating,violence,world/life,...,sadness,feelings,danceability,loudness,acousticness,instrumentalness,valence,energy,topic,age
0,0,mukesh,mohabbat bhi jhoothi,1950,pop,hold time feel break feel untrue convince spea...,95,0.000598,0.063746,0.000598,...,0.380299,0.117175,0.357739,0.454119,0.997992,0.901822,0.339448,0.137110,sadness,1.000000
1,4,frankie laine,i believe,1950,pop,believe drop rain fall grow believe darkest ni...,51,0.035537,0.096777,0.443435,...,0.001284,0.001284,0.331745,0.647540,0.954819,0.000002,0.325021,0.263240,world/life,1.000000
2,6,johnnie ray,cry,1950,pop,sweetheart send letter goodbye secret feel bet...,24,0.002770,0.002770,0.002770,...,0.002770,0.225422,0.456298,0.585288,0.840361,0.000000,0.351814,0.139112,music,1.000000
3,10,p√©rez prado,patricia,1950,pop,kiss lips want stroll charm mambo chacha merin...,54,0.048249,0.001548,0.001548,...,0.225889,0.001548,0.686992,0.744404,0.083935,0.199393,0.775350,0.743736,romantic,1.000000
4,12,giorgos papadopoulos,apopse eida oneiro,1950,pop,till darling till matter know till dream live ...,48,0.001350,0.001350,0.417772,...,0.068800,0.001350,0.291671,0.646489,0.975904,0.000246,0.597073,0.394375,romantic,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28367,82447,mack 10,10 million ways,2019,hip hop,cause fuck leave scar tick tock clock come kno...,78,0.001350,0.001350,0.001350,...,0.065664,0.001350,0.889527,0.759711,0.062549,0.000000,0.751649,0.695686,obscene,0.014286
28368,82448,m.o.p.,ante up (robbin hoodz theory),2019,hip hop,minks things chain ring braclets yap fame come...,67,0.001284,0.001284,0.035338,...,0.001284,0.001284,0.662082,0.789580,0.004607,0.000002,0.922712,0.797791,obscene,0.014286
28369,82449,nine,whutcha want?,2019,hip hop,get ban get ban stick crack relax plan attack ...,77,0.001504,0.154302,0.168988,...,0.001504,0.001504,0.663165,0.726970,0.104417,0.000001,0.838211,0.767761,obscene,0.014286
28370,82450,will smith,switch,2019,hip hop,check check yeah yeah hear thing call switch g...,67,0.001196,0.001196,0.001196,...,0.001196,0.001196,0.883028,0.786888,0.007027,0.000503,0.508450,0.885882,obscene,0.014286
28371,82451,jeezy,r.i.p.,2019,hip hop,remix killer alive remix thriller trap bitch s...,83,0.001012,0.075202,0.001012,...,0.001012,0.033995,0.828875,0.674794,0.015862,0.000000,0.475474,0.492477,obscene,0.014286

In [5]:
df.isna().sum()

Unnamed: 0                  0
artist_name                 0
track_name                  0
release_date                0
genre                       0
lyrics                      0
len                         0
dating                      0
violence                    0
world/life                  0
night/time                  0
shake the audience          0
family/gospel               0
romantic                    0
communication               0
obscene                     0
music                       0
movement/places             0
light/visual perceptions    0
family/spiritual            0
like/girls                  0
sadness                     0
feelings                    0
danceability                0
loudness                    0
acousticness                0
instrumentalness            0
valence                     0
energy                      0
topic                       0
age                         0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28372 entries, 0 to 28371
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                28372 non-null  int64
 1   artist_name               28372 non-null  object
 2   track_name                28372 non-null  object
 3   release_date              28372 non-null  int64
 4   genre                     28372 non-null  object
 5   lyrics                    28372 non-null  object
 6   len                       28372 non-null  int64
 7   dating                    28372 non-null  float64
 8   violence                  28372 non-null  float64
 9   world/life                28372 non-null  float64
 10  night/time                28372 non-null  float64
 11  shake the audience        28372 non-null  float64
 12  family/gospel             28372 non-null  float64
 13  romantic                  28372 non-null  float64
 14  communication             28372 non-null  float64
 15  obscene                   28372 non-null  float64
 16  music                     28372 non-null  float64
 17  movement/places           28372 non-null  float64
 18  light/visual perceptions  28372 non-null  float64
 19  family/spiritual          28372 non-null  float64
 20  like/girls                28372 non-null  float64
 21  sadness                   28372 non-null  float64
 22  feelings                  28372 non-null  float64
 23  danceability              28372 non-null  float64
 24  loudness                  28372 non-null  float64
 25  acousticness              28372 non-null  float64
 26  instrumentalness          28372 non-null  float64
 27  valence                   28372 non-null  float64
 28  energy                    28372 non-null  float64
 29  topic                     28372 non-null  object
 30  age                       28372 non-null  float64
dtypes: float64(23), int64(3), object(5)
memory usage: 6.7+ MB

In [7]:
collected= df[['track_name','artist_name','genre', 'release_date', 'topic', 'len']]

In [8]:
collected

,track_name,artist_name,genre,release_date,topic,len
0,mohabbat bhi jhoothi,mukesh,pop,1950,sadness,95
1,i believe,frankie laine,pop,1950,world/life,51
2,cry,johnnie ray,pop,1950,music,24
3,patricia,p√©rez prado,pop,1950,romantic,54
4,apopse eida oneiro,giorgos papadopoulos,pop,1950,romantic,48
...,...,...,...,...,...,...
28367,10 million ways,mack 10,hip hop,2019,obscene,78
28368,ante up (robbin hoodz theory),m.o.p.,hip hop,2019,obscene,67
28369,whutcha want?,nine,hip hop,2019,obscene,77
28370,switch,will smith,hip hop,2019,obscene,67
28371,r.i.p.,jeezy,hip hop,2019,obscene,83

In [9]:
collected= collected.rename(columns={'artist_name': 'Artist', 'track_name': 'Song_title'})

In [10]:
collected

,Song_title,Artist,genre,release_date,topic,len
0,mohabbat bhi jhoothi,mukesh,pop,1950,sadness,95
1,i believe,frankie laine,pop,1950,world/life,51
2,cry,johnnie ray,pop,1950,music,24
3,patricia,p√©rez prado,pop,1950,romantic,54
4,apopse eida oneiro,giorgos papadopoulos,pop,1950,romantic,48
...,...,...,...,...,...,...
28367,10 million ways,mack 10,hip hop,2019,obscene,78
28368,ante up (robbin hoodz theory),m.o.p.,hip hop,2019,obscene,67
28369,whutcha want?,nine,hip hop,2019,obscene,77
28370,switch,will smith,hip hop,2019,obscene,67
28371,r.i.p.,jeezy,hip hop,2019,obscene,83

In [11]:
random_songs= collected.sample(n=3000, random_state=1)

In [12]:
random_songs

,Song_title,Artist,genre,release_date,topic,len
19004,the little man who wasn't there,glenn miller,jazz,1991,sadness,59
25729,american psycho,misfits,rock,1997,violence,95
4826,somebody that i used to know,elliott smith,pop,2000,sadness,33
7082,juke box blues,june carter cash,country,1952,music,75
18095,"karn evil 9 1st impression, pt. 1","emerson, lake & palmer",jazz,1973,violence,95
...,...,...,...,...,...,...
25117,reckless life,guns n' roses,rock,1988,world/life,70
13874,pain and love,t. rex,blues,1977,world/life,98
16983,brave new world,greta van fleet,blues,2018,violence,66
21878,i-76,g. love & special sauce,reggae,1994,obscene,169
7837,just out of reach (of my two open arms),patsy cline,country,1965,sadness,44

In [13]:
not_so_hot_songs= random_songs

In [14]:
not_so_hot_songs = not_so_hot_songs.reset_index(drop=True)

In [15]:
not_so_hot_songs

,Song_title,Artist,genre,release_date,topic,len
0,the little man who wasn't there,glenn miller,jazz,1991,sadness,59
1,american psycho,misfits,rock,1997,violence,95
2,somebody that i used to know,elliott smith,pop,2000,sadness,33
3,juke box blues,june carter cash,country,1952,music,75
4,"karn evil 9 1st impression, pt. 1","emerson, lake & palmer",jazz,1973,violence,95
...,...,...,...,...,...,...
2995,reckless life,guns n' roses,rock,1988,world/life,70
2996,pain and love,t. rex,blues,1977,world/life,98
2997,brave new world,greta van fleet,blues,2018,violence,66
2998,i-76,g. love & special sauce,reggae,1994,obscene,169
2999,just out of reach (of my two open arms),patsy cline,country,1965,sadness,44

In [16]:
df2= pd.read_csv('billboard_top_100.csv')

In [17]:
df2

,Unnamed: 0,Song_title,Artist
0,0,Rockin' Around The Christmas Tree,Brenda Lee
1,1,All I Want For Christmas Is You,Mariah Carey
2,2,Jingle Bell Rock,Bobby Helms
3,3,Last Christmas,Wham!
4,4,A Holly Jolly Christmas,Burl Ives
...,...,...,...
95,95,El Amor de Su Vida,Grupo Frontera & Grupo Firme
96,96,Standing Next To You,Jung Kook
97,97,Man Made A Bar,Morgan Wallen Featuring Eric Church
98,98,Que Onda,Calle 24 x Chino Pacas x Fuerza Regida
99,99,Great Gatsby,Rod Wave

In [18]:
df2=df2.drop(columns={'Unnamed: 0'})

In [19]:
df2

                           Song_title                                  Artist
0   Rockin' Around The Christmas Tree                              Brenda Lee
1     All I Want For Christmas Is You                            Mariah Carey
2                    Jingle Bell Rock                             Bobby Helms
3                      Last Christmas                                   Wham!
4             A Holly Jolly Christmas                               Burl Ives
..                                ...                                     ...
95                 El Amor de Su Vida            Grupo Frontera & Grupo Firme
96               Standing Next To You                               Jung Kook
97                     Man Made A Bar     Morgan Wallen Featuring Eric Church
98                           Que Onda  Calle 24 x Chino Pacas x Fuerza Regida
99                       Great Gatsby                                Rod Wave

[100 rows x 2 columns]

In [20]:
hot_songs= df2

In [21]:
#Gather the songs
#Remove songs already present in the hot_songs dataset

In [22]:
def exclude_overlapping_songs(hot_songs, not_so_hot_songs, Artist, Song_title):
    """
    Exclude songs from hot_songs_df that are present in not_hot_songs_df.

    :param hot_songs: DataFrame containing hot songs.
    :param not_hot_songs: DataFrame containing not hot songs.
    :param Artist: Column name for artist in both DataFrames.
    :param Song_title: Column name for song title in both DataFrames.
    :return: DataFrame of hot songs excluding those present in not hot songs.
    """

    hot_songs['combined_key'] = hot_songs[Artist] + ' - ' + hot_songs[Song_title]
    not_so_hot_songs['combined_key'] = not_so_hot_songs[Artist] + ' - ' + not_so_hot_songs[Song_title]

    mask = hot_songs['combined_key'].isin(not_so_hot_songs['combined_key'])

    exclusive_hot_songs= hot_songs[~mask].copy()

    exclusive_hot_songs.drop(columns=['combined_key'], inplace=True)

    return exclusive_hot_songs

In [23]:
exclusive_hot_songs = exclude_overlapping_songs(hot_songs, not_so_hot_songs, 'Artist', 'Song_title')

print("Number of exclusive hot songs:", len(exclusive_hot_songs))

Number of exclusive hot songs: 100

In [24]:
exclusive_hot_songs

                           Song_title                                  Artist
0   Rockin' Around The Christmas Tree                              Brenda Lee
1     All I Want For Christmas Is You                            Mariah Carey
2                    Jingle Bell Rock                             Bobby Helms
3                      Last Christmas                                   Wham!
4             A Holly Jolly Christmas                               Burl Ives
..                                ...                                     ...
95                 El Amor de Su Vida            Grupo Frontera & Grupo Firme
96               Standing Next To You                               Jung Kook
97                     Man Made A Bar     Morgan Wallen Featuring Eric Church
98                           Que Onda  Calle 24 x Chino Pacas x Fuerza Regida
99                       Great Gatsby                                Rod Wave

[100 rows x 2 columns]

In [25]:
exclusive_hot_songs.to_csv('exclusive_hot_songs.csv', index=False)